spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    web:
      pageable:
        max-page-size: 100000000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
      format_sql: true
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
#    url: jdbc:h2:~/data/cloudstock
    url: jdbc:mysql://mariadb:3307/clouddb
    out-of-order: true
  h2:
    console:
      enabled: true
jwt:
  secret: "breadstockcloud"

server:
  tomcat:
    uri-encoding: UTF-8


---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: dev