spring:
  datasource:
    url: jdbc:h2:~/data/cloudstock
    username: sa
    password:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  h2:
    console:
      enabled: true
logging:
  level:
    jdbc: trace