spring:
  kafka:
    bootstrap-servers: 192.168.29.189:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://192.168.29.189:3307/clouddb
    username: root
    password: P!ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:~/data/cloudstock
#    username: sa
#    password:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
      format_sql: true
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
#    url: jdbc:h2:~/data/cloudstock
    url: jdbc:mysql://192.168.29.189:3307/clouddb
    out-of-order: true
  h2:
    console:
      enabled: true
logging:
  level:
    jdbc: trace
    root: DEBUG
jwt:
  secret: "breadstockcloud"
