name: Docker Image CI

on:
  push:
    branches:
      - 'dev'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build the Docker image
      env:
        NAME: hencyyeo
        REPO: cloud-alarm-server-renewal
      run: |
        docker build --platform linux/amd64 -t $REPO:dev-v0.0.5-rc10 .
        docker tag $REPO:dev-v0.0.5-rc10 $NAME/$REPO:dev-v0.0.5-rc10
        docker push $NAME/$REPO:dev-v0.0.5-rc10
